services:
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=BookStore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5442:5432

volumes:
  database_data:
    driver: local